FROM ubuntu:18.04

LABEL maintainer="paulokinjo@hotmail.com"

RUN apt-get update -y && \
  apt-get install \
  vim \
  sshpass \
  net-tools \
  ssh \
  openssh-client \
  openssh-server \
  locales \
  iputils-ping -y 

# remove some pointless services
RUN /usr/sbin/update-rc.d -f ondemand remove; \
  for f in \
  /etc/init/u*.conf \
  /etc/init/mounted-dev.conf \
  /etc/init/mounted-proc.conf \
  /etc/init/mounted-run.conf \
  /etc/init/mounted-tmp.conf \
  /etc/init/mounted-var.conf \
  /etc/init/hostname.conf \
  /etc/init/networking.conf \
  /etc/init/tty*.conf \
  /etc/init/plymouth*.conf \
  /etc/init/hwclock*.conf \
  /etc/init/module*.conf\
  ; do \
  dpkg-divert --local --rename --add "$f"; \
  done; \
  echo '# /lib/init/fstab: cleared out for bare-bones Docker' > /lib/init/fstab

RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

RUN ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa

RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

# supervisor installation &&
# create directory for child images to store configuration in
RUN apt-get -y install supervisor && \
  mkdir -p /var/log/supervisor && \
  mkdir -p /etc/supervisor/conf.d

# supervisor base configuration 
ADD supervisor.conf /etc/supervisor.conf

EXPOSE 22

# default command
CMD ["supervisord", "-c", "/etc/supervisor.conf"]
