apiVersion: v1
kind: ReplicationController
metadata:
  name: hlld-controller
spec:
  replicas: 2
  selector:
    app: hlld
  template:
    metadata:
      name: hlld
      labels:
        app: hlld
    spec:
      containers:
        - name: k8s-demo
          image: wardviaene/k8s-demo
          ports:
            - name: nodejs-port
              containerPort: 3000
