apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlld-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hlld-deployment
  template:
    metadata:
      labels:
        app: hlld-deployment
    spec:
      containers:
      - name: k8s-demo  
        image: wardviaene/k8s-demo:2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: nodejs-port
          containerPort: 3000
