apiVersion: v1
kind: Pod
metadata:
  name: nodehlld.ex.com
  labels:
    name: hlld
spec:
  containers:
  - name: k8s-demo
    image: wardviaene/k8s-demo
    resources:
      limits:
        memory: "256Mi"
        cpu: "750m"
    ports:
      - name: nodejs-port
        containerPort: 3000
