FROM paulokinjo/pk-ubuntu

LABEL maintainer="paulokinjo@hotmail.com"

RUN apt install -y software-properties-common                   

RUN add-apt-repository ppa:deadsnakes/ppa -y 

RUN apt install python3.7 -y

